# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [
    "amdgpu"
    "nvme"
  ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/7fcb658c-3939-4553-b020-3ca59ff32a0f";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-f9f2d44f-903d-4646-b9ae-9ac7d430853c".device =
    "/dev/disk/by-uuid/f9f2d44f-903d-4646-b9ae-9ac7d430853c";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/A5D5-8A5F";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  # Patriot NVME 1TB
  fileSystems."/mnt/games" = {
    device = "/dev/disk/by-uuid/778e7160-661b-4235-85fe-b8ddbb1e061d";
    fsType = "btrfs";
    options = [
      "nofail"
      "compress=zstd" # Enables transparent zstd compression
      "noatime" # Improves performance by not writing access times
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/3f9cb9ca-4054-4dfa-9086-0d73dcfe5cc7"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp42s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
