# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = [
    "ata_piix"
    "xhci_pci"
    "virtio_pci"
    "ahci"
    "sr_mod"
    "virtio_blk"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/eab38bc7-8b18-4070-9e85-7fa344df4179";
    fsType = "ext4";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/0a001af0-4b5c-463d-b830-6309082b39e9"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
